-- Warning: You can generate script only for one table/view at a time in your Free plan 
-- 
-- **************************** SqlDBM: MySQL ***************************
-- ******* Generated by SqlDBM: j-stalk, v8 by lea.grave@orange.fr ******

-- ************************************** `User`

CREATE TABLE `User`
(
 `userID`      int NOT NULL ,
 `password`    varchar(15) NOT NULL ,
 `name`        varchar(45) NOT NULL ,
 `firstName`   varchar(45) NOT NULL ,
 `phoneNumber` int NOT NULL ,
 `pictures`    varchar(250) NULL ,

PRIMARY KEY (`userID`)
);





-- ************************************** `Teacher`

CREATE TABLE `Teacher`
(
 `teacherID` int NOT NULL ,
 `userID`    int NOT NULL ,

PRIMARY KEY (`teacherID`),
KEY `FK_2` (`userID`),
CONSTRAINT `FK_4` FOREIGN KEY `FK_2` (`userID`) REFERENCES `User` (`userID`)
);



-- ************************************** `student`

CREATE TABLE `student`
(
 `studentID`   int NOT NULL ,
 `userID`      int NOT NULL ,
 `contratType` varchar(45) NOT NULL ,
 `postType`    varchar(45) NOT NULL ,
 `yearSchool`  varchar(45) NOT NULL ,

PRIMARY KEY (`studentID`),
KEY `FK_3` (`userID`),
CONSTRAINT `FK_3` FOREIGN KEY `FK_3` (`userID`) REFERENCES `User` (`userID`)
);





-- ************************************** `Adress`

CREATE TABLE `Adress`
(
 `adressID`   int NOT NULL ,
 `adress`     varchar(250) NOT NULL ,
 `city`       varchar(50) NOT NULL ,
 `postalCode` int NOT NULL ,

PRIMARY KEY (`adressID`)
);




-- ************************************** `News`

CREATE TABLE `News`
(
 `newsID`       int NOT NULL ,
 `titleNews`    varchar(50) NOT NULL ,
 `typePost`     varchar(100) NOT NULL ,
 `duration`     timestamp NOT NULL ,
 `contractType` varchar(100) NOT NULL ,
 `price`        int NOT NULL ,

PRIMARY KEY (`newsID`)
);





-- ************************************** `compagny`

CREATE TABLE `compagny`
(
 `compagnyID` int NOT NULL ,
 `adressID`   int NOT NULL ,
 `newsID`     int NOT NULL ,
 `userID`     int NOT NULL ,

PRIMARY KEY (`compagnyID`),
KEY `FK_2` (`adressID`),
CONSTRAINT `FK_2` FOREIGN KEY `FK_2` (`adressID`) REFERENCES `Adress` (`adressID`),
KEY `FK_3` (`userID`),
CONSTRAINT `FK_5` FOREIGN KEY `FK_3` (`userID`) REFERENCES `User` (`userID`),
KEY `FK_4` (`newsID`),
CONSTRAINT `FK_6` FOREIGN KEY `FK_4` (`newsID`) REFERENCES `News` (`newsID`)
);



-- ************************************** `School`

CREATE TABLE `School`
(
 `schoolID`   int NOT NULL ,
 `schoolName` varchar(100) NOT NULL ,
 `studentID`  int NOT NULL ,
 `teacherID`  int NOT NULL ,
 `adressID`   int NOT NULL ,

PRIMARY KEY (`schoolID`),
KEY `FK_2` (`adressID`),
CONSTRAINT `FK_7` FOREIGN KEY `FK_2` (`adressID`) REFERENCES `Adress` (`adressID`),
KEY `FK_3` (`teacherID`),
CONSTRAINT `FK_8` FOREIGN KEY `FK_3` (`teacherID`) REFERENCES `Teacher` (`teacherID`),
KEY `FK_4` (`studentID`),
CONSTRAINT `FK_9` FOREIGN KEY `FK_4` (`studentID`) REFERENCES `student` (`studentID`)
);






-- ************************************** `Document`

CREATE TABLE `Document`
(
 `documentID` int NOT NULL ,
 `name`       varchar(45) NOT NULL ,
 `typeDoc`    varchar(45) NOT NULL ,

PRIMARY KEY (`documentID`)
);










